version: '3.8'
services:
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./app:/var/www/app
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
        working_dir: /var/www/app
        depends_on:
            - php-fpm

    php-cli:
        build:
            context: .
            dockerfile: ./docker/php/php-cli.docker
        environment:
            APP_ENV: dev
        volumes:
            - ./app:/var/www/app
        working_dir: /var/www/app
        depends_on:
            - mysql

    php-fpm:
        build:
            context: .
            dockerfile: ./docker/php/php-fpm.docker
        environment:
            APP_ENV: dev
        volumes:
            - ./app:/var/www/app
        working_dir: /var/www/app
        depends_on:
            - mysql

    mysql:
        image: mysql:latest
#        restart: always
        volumes:
            - mysqldata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: bnb
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            MYSQL_USER: bnb
        ports:
            - "3306:3306"

    manager-node:
        image: node:current-alpine
        volumes:
            - ./app:/var/www/app
        working_dir: /var/www/app

    mailer:
        image: mailhog/mailhog
        ports:
            - "8082:8025"

volumes:
    mysqldata:
        driver: local